/* $Id$
 * 
 * Part of ZonMW project no. 50-53000-98-156
 * 
 * @license
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 * 
 * Copyright (c) 2016 RIVM National Institute for Health and Environment 
 */
package nl.rivm.cib.episim.model;

import io.coala.time.x.Duration;
import io.coala.time.x.Instant;

/**
 * {@link ContactEvent} generated by some {@link Location} represents the
 * interval ({@link #getStart()} and {@link #getDuration()}) at some
 * {@link Location} when a primary {@link Carrier} (e.g. carrying some
 * {@link Infection} at infective {@link EpidemicCompartment}) shared some transmission
 * {@link TransmissionRoute} with some secondary (possibly) susceptible
 * {@link Carrier}
 * 
 * @version $Id$
 * @author Rick van Krevelen
 */
public interface ContactEvent
{
	/** @return the contact onset {@link Instant} */
	Instant getStart();

	/** @return the contact {@link Duration} */
	Duration getDuration();

	/** @return the contact {@link Location} */
	Location getLocation();

	/** @return the contact transmission {@link TransmissionRoute} */
	TransmissionRoute getTransmissionRoute();

	/**
	 * @return the {@link Condition} of the primary (infective) {@link Carrier}
	 */
	Condition getPrimaryCondition();

	/**
	 * @return the {@link Condition} of the secondary (susceptible)
	 *         {@link Carrier}
	 */
	Condition getSecondaryCondition();

}